### ISSUE TITLE
move config file out of docker container

### ISSUE THREAD

**Issue by benedikt-bartscher** [numberly/gitlab2sentry#8]
either mount configfile as kubernetes secret/configmap or allow full configuration with environment variables

**Comment by thepetk** [comment]
Hi!

Thank you for your interest in the project!

IMO this could be a very good iteration over the configuration of the project.

**Comment by thepetk** [comment]
closed by https://github.com/numberly/gitlab2sentry/pull/12

The ```g2s.yaml``` has been removed. The configuration will now be handled via ```helm/values-production.yaml``` secrets
