### ISSUE TITLE
add cicd

### ISSUE THREAD

**Issue by benedikt-bartscher** [numberly/gitlab2sentry#9]
I created a .gitlab-ci.yml to build container images via kaniko. Do you host this repo on gitlab too? I could share my .gitlab-ci.yml so you could push images to docker hub for example.

**Comment by thepetk** [comment]
Hi again!

Though we don't have the exact same repo on gitlab too, but we are using kaniko with gitlab-ci and this repo to create our automation with gitlab2sentry. As this repo stands like an example solution right now, we don't have added CI CD yet :)

IMO it would be very nice to share it on this thread, it could help other people who are looking for the same solution!

Thanks!

**Comment by benedikt-bartscher** [comment]
I think it would be better to first solve #8 and then provide a image to docker hub. But either way, heres a simple .gitlab-ci.yml if someone wants to build his own images via gitlab-ci:

```
stages:
  - build

variables:
  DOCKERFILE: "${CI_PROJECT_DIR}/Dockerfile"
  IMAGEBASE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --snapshot-mode=redo
      --use-new-run
      --cache=true
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${DOCKERFILE}"
      --destination "${IMAGEBASE}"
```

**Comment by thepetk** [comment]
Thanks a lot @benedikt-bartscher ! Yes for this I have opened a branch, for issue #8 and we are currently working on it! Thanks for reporting. I will close this issue and we can expand on #8 :)
